#!/usr/bin/env python3

import argparse
import subprocess
import time
import logging

logging.basicConfig()
log = logging.root
log.name = "retry-command"
log.setLevel(logging.INFO)

def runCommand(args):
    retry = 0
    while retry < args.retries:
        logging.info("Run command (retry %s): %s", retry, args.args)
        try:
            subprocess.check_output(args.args)
            return
        except subprocess.CalledProcessError:
            logging.info("Failed. Waiting %ss", args.wait)
            time.sleep(args.wait)
        retry += 1
    pass

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description='Retries command with wait time in between.')
    parser.add_argument('--retries', metavar='retries', type=int, default=10,
                        help='how many retries')
    parser.add_argument('--wait', metavar='wait', type=int, default=15,
                        help='seconds to wait between retries')
    parser.add_argument('args', metavar='args', nargs="*",
                        help='command and arguments to run')

    args = parser.parse_args()

    runCommand(args)
