---
name: Check shell syntax

on:
  push:
    paths:
      - '**.sh'
      - .github/workflows/syntax-shell.yml
  pull_request:
    paths:
      - '**.sh'
      - .github/workflows/syntax-shell.yml

jobs:
  shellcheck:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS:
